<?php

namespace AppBundle\Repository;

/**
 * RandomNumberRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class RandomNumberRepository extends \Doctrine\ORM\EntityRepository
{
}
